### ISSUE TITLE
Visual Studio Version Mismatch

### ISSUE THREAD

**Issue by Dokman** [LDOpenSource/DarkSoul#2]
D:\Repos\DarkSoul\DarkSoul.GUI.World\DarkSoul.GUI.World.csproj : error  : El espacio de nombres XML del proyecto debe ser el espacio de nombres XML de MSBuild. Si el proyecto se creó con el formato MSBuild 2003, agregue xmlns="http://schemas.microsoft.com/developer/msbuild/2003" al elemento <Project>. Si se creó con el formato 1.0 ó 1.2 anterior, conviértalo al formato MSBuild 2003.  D:\Repos\DarkSoul\DarkSoul.GUI.World\DarkSoul.GUI.World.csproj

D:\Repos\DarkSoul\DarkSoul.Network\DarkSoul.Network.csproj : error  : El espacio de nombres XML del proyecto debe ser el espacio de nombres XML de MSBuild. Si el proyecto se creó con el formato MSBuild 2003, agregue xmlns="http://schemas.microsoft.com/developer/msbuild/2003" al elemento <Project>. Si se creó con el formato 1.0 ó 1.2 anterior, conviértalo al formato MSBuild 2003.  D:\Repos\DarkSoul\DarkSoul.Network\DarkSoul.Network.csproj

D:\Repos\DarkSoul\DarkSoul.GUI.Auth\DarkSoul.GUI.Auth.csproj : error  : El espacio de nombres XML del proyecto debe ser el espacio de nombres XML de MSBuild. Si el proyecto se creó con el formato MSBuild 2003, agregue xmlns="http://schemas.microsoft.com/developer/msbuild/2003" al elemento <Project>. Si se creó con el formato 1.0 ó 1.2 anterior, conviértalo al formato MSBuild 2003.  D:\Repos\DarkSoul\DarkSoul.GUI.Auth\DarkSoul.GUI.Auth.csproj

D:\Repos\DarkSoul\DarkSoul.Core\DarkSoul.Core.csproj : error  : El espacio de nombres XML del proyecto debe ser el espacio de nombres XML de MSBuild. Si el proyecto se creó con el formato MSBuild 2003, agregue xmlns="http://schemas.microsoft.com/developer/msbuild/2003" al elemento <Project>. Si se creó con el formato 1.0 ó 1.2 anterior, conviértalo al formato MSBuild 2003.  D:\Repos\DarkSoul\DarkSoul.Core\DarkSoul.Core.csproj

**Comment by WolfDan** [comment]
Entre los requisitos esta tener visual studio 2017 

Tener en cuenta instalado el paquete de .net core y .net standard

**Comment by Dokman** [comment]
ok gracias por el aviso tengo el 2015, voy a por el 2017 entonces ;)
