### ISSUE TITLE
Chat de equipo

### ISSUE THREAD

**Issue by Radigar** [LDOpenSource/DarkSoul#5]
Lo primero de todo felicitaros por la buena iniciativa que estáis creando. Me gustaría saber si tenéis algún chat de equipo como Slack, Discord o si teneis pensado crearlo donde el flujo de información entre los desarrolladores sea fluido.

Muchas gracias, un saludo.

**Comment by WolfDan** [comment]
Hola y gracias por estar interesado en el proyecto, por el momento nunca pense en algo como ello, pero siente libre de crearlo y compartirlo!

**Comment by Radigar** [comment]
Hay una herramienta de chat perfecta para estos casos [Gitter](https://gitter.im) que se vincula automáticamente con el repositorio que tengas en github y donde puedes ver notificaciones relacionadas con el proyecto. Lo lógico es que quien gestione este repositorio lo haga ya que va a poder asociarlo desde su cuenta.

**Comment by WolfDan** [comment]
Hola, disculpa la demora he estado ocupado, muy bien añadiremos Gitter en cuanto me den acceso a los settings del grupo
